export AWS_AUTO_SCALING_HOME="/opt/aws/apitools/as"
export AWS_CLOUDWATCH_HOME="/opt/aws/apitools/mon"
export AWS_ELB_HOME="/opt/aws/apitools/elb"
export AWS_IAM_HOME="/opt/aws/apitools/iam"
export AWS_PATH="/opt/aws"
export AWS_RDS_HOME="/opt/aws/apitools/rds"
export EC2_AMITOOL_HOME="/opt/aws/amitools/ec2"
export EC2_HOME="/opt/aws/apitools/ec2"
export G_BROKEN_FILENAMES="1"
export INPUTRC="/etc/inputrc"
export JAVA_HOME="/usr/lib/jvm/jre"
export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin"
export SHELL="/bin/bash"
/home/ec2-user/backup/backup_script.py
